amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: base_link
    global_frame_id: map
    odom_frame_id: odom
    laser_model_type: likelihood_field
    max_particles: 2000
    min_particles: 500
    robot_model_type: nav2_amcl::DifferentialMotionModel
    scan_topic: /scan
    tf_broadcast: true
    transform_tolerance: 1.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: progress_checker
    goal_checker_plugins: [general_goal_checker]
    controller_plugins: [FollowPath]

    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker

    FollowPath:
      plugin: dwb_core::DWBLocalPlanner
      debug_trajectory_details: True
      min_vel_x: 0.0
      max_vel_x: 0.26
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      min_theta_velocity_threshold: 0.001
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      transform_tolerance: 0.2
      short_circuit_trajectory_evaluation: True
      critics: [RotateToGoal, Oscillation, BaseObstacle, GoalAlign, PathAlign, PathDist, GoalDist]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0

    progress_checker:
      plugin: nav2_controller::SimpleProgressChecker

planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 20.0
    planner_plugins: [GridBased]
    GridBased:
      plugin: nav2_navfn_planner/NavfnPlanner

behavior_server:
  ros__parameters:
    use_sim_time: True
    local_costmap_topic: /local_costmap/costmap_raw
    global_costmap_topic: /global_costmap/costmap_raw
    local_frame: odom

waypoint_follower:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: True
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.22
      plugins: [obstacle_layer, inflation_layer]
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.0
          obstacle_max_range: 4.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        cost_scaling_factor: 3.0
        inflation_radius: 0.45

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      resolution: 0.05
      robot_radius: 0.22
      plugins: [static_layer, obstacle_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
      obstacle_layer:
        plugin: nav2_costmap_2d::ObstacleLayer
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
